### ISSUE TITLE
Add help text will probably need a lot more info

### ISSUE THREAD

**Issue by kmugrage** [devopsdays/devopsdays-cli#70]
With the usage really be `devopsdays-cli add [command]`?

I expected to be able to say something like `devopsdays-cli add sponsor chef 2018-test-city`

Of course as soon as I type that I realize it's incredibly unlikely people would format the city correctly. Feel free to close this with no action, but opening it anyway 'cause it's early in the system's life and I noticed.

![image](https://user-images.githubusercontent.com/3209933/31133826-5e8b16cc-a815-11e7-95e7-80debd502aef.png)

**Comment by mattstratton** [comment]
Now it looks a little more like this (granted, the add thing isn't quite up to snuff, but is this more what you meant?)

```
$ devopsdays-cli create speaker -h
Creates a new speaker for an event.                                                                                                 
You can provide the speaker's name as an argument to this command, but it must be the "cleaned" name.

Usage:
  devopsdays-cli create speaker [flags]

Examples:
  devopsdays-cli create speaker george-bluth
  devopsdays-cli create speaker --city new-york
  devopsdays-cli create speaker george-bluth -c "New York" --year "2017"

Flags:
  -c, --city string   city to use
  -h, --help          help for speaker
  -y, --year string   year to use

Global Flags:
  -d, --debug   enable debug mode
```

Although this is where using the namespacing I mentioned in #71 might come into play, so the command would be more like `devopsdays-cli create:speaker george-bluth`

Generally speaking, except for city and sponsor, the `create` verb with the name argument isn't that useful, because it requires really figuring it out.

**Comment by mattstratton** [comment]
I think this was more informational than anything. We keep interatinf to improve the inline help.
